todoリストをReduxを用いて書き換える
shirasu-aq/todoList_redux pull request #7
Opened 2021-07-27 08:57 UTC by shirasu-aq

2021-07-27 09:10 UTC, shirasu-aq commented on src/components/features/posts/postlist/postsSlice.js
> +    },
**[Q]**
```.push```を使わずに```[...state, action.payload]```の方が好ましいでしょうか？
公式のチュートリアルでは.pushを使用していました。

参考：
https://frontedcode.com/posts/frontend/react/5
https://qiita.com/kuropp/items/f295c45e1705677a7a48

2021-07-27 09:27 UTC, shirasu-aq commented on src/components/features/posts/addpostform/index.jsx
> +  };
[Q]
Reactの時は親でイベントを定義したり、stateを保持したりして、子では使うときに呼び出すようにしたのですが、reduxもそうした方が良いのでしょうか？

親に ```setTask("")```（todo登録後、入力フォームを空にするイベント）を持たせると空にならず、登録ボタンと同じファイル内に置き直したところ、空になったのでrenderの関係かな、と思いました。

2021-07-27 09:29 UTC, shirasu-aq commented
チュートリアルに沿って、まずはswitch case文を使わないで実装してみました。
予定通り動いてはいるのですが、あまり自信がないので全体的にコードの書き方を見ていただきたいです。

2021-07-28 03:43 UTC, tatsuya-asami requested changes

2021-07-28 03:43 UTC, tatsuya-asami commented on .vscode/settings.json
> +}
改行

2021-07-28 04:02 UTC, shirasu-aq commented on .vscode/settings.json
> +}
ef8e086　修正しました。

2021-07-28 08:47 UTC, tatsuya-asami commented on src/components/features/posts/postlist/postsSlice.js
> +    },
toolkitが内部で持っているimmerが破壊的な変更をしないようにしてくれているのでpushでも問題なく動くのだと思います。
なのでtoolkitを使っている場合はどちらでも問題ないと思います。

2021-07-28 08:58 UTC, tatsuya-asami requested changes
redux使う意味がほとんどないので逆にわかりにくくなったかもしれませんが、reduxの書き方自体は問題ないと思います。

2021-07-28 08:58 UTC, tatsuya-asami commented on src/components/features/posts/postsSlice.js
> +import { createSlice } from "@reduxjs/toolkit";
sliceはcomponentではないのでここにあるのはおかしいです。
src/reduxとかを作って、redux関連のファイルはそこに入れればわかりやすいと思います。

2021-07-28 08:58 UTC, tatsuya-asami commented on src/components/features/posts/postsSlice.js
> +      state.splice(0);
spliceの本来の使い方と異なるのでわかりにくいと思います。initalStateをセットし直すのがわかりやすいと思います。
```
return initialState
```

2021-07-28 09:32 UTC, shirasu-aq commented on src/components/features/posts/postlist/postsSlice.js
> +    },
なるほどです！
承知しました。

2021-07-28 09:41 UTC, shirasu-aq commented on src/components/features/posts/postsSlice.js
> +      state.splice(0);
承知しました。
ad988ac 修正しました。

2021-07-28 09:41 UTC, shirasu-aq commented on src/components/features/posts/postsSlice.js
> +import { createSlice } from "@reduxjs/toolkit";
660cd1e　修正しました。

2021-07-28 10:14 UTC, tatsuya-asami commented on src/components/features/posts/postsSlice.js
> +import { createSlice } from "@reduxjs/toolkit";
src/app/store.js もredux関連のファイルだと思うので同じディレクトリに入れた方が良いと思います。

2021-07-28 10:15 UTC, tatsuya-asami requested changes

2021-07-28 10:15 UTC, tatsuya-asami commented on src/redux/postsSlice.js
> +export default postsSlice.reducer;
- nits
default exportにしないといけない理由はないと思うのでやめた方が良いです。

2021-07-29 00:47 UTC, shirasu-aq commented on src/components/features/posts/postsSlice.js
> +import { createSlice } from "@reduxjs/toolkit";
0979fe5 修正しました。

2021-07-29 00:47 UTC, shirasu-aq commented on src/redux/postsSlice.js
> +export default postsSlice.reducer;
b61c657 修正しました。

2021-07-29 01:03 UTC, tatsuya-asami approved these changes

2021-07-29 02:08 UTC, merged